apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: IoT-smart-meter
      defaultBucket: smart-meter
      tlsSkipVerify: true
    secureJsonData:
      token: mytoken